### ISSUE TITLE
Best way to run against a cljs application?

### ISSUE THREAD

**Issue by kovasap** [jpmonettas/flow-storm-debugger#42]
I'm working on a node.js CLJS project, and am curious about how others are hooking in flowstorm to their workflow.

Right now, if I know I have some bug in one of my files, I add `[flow-storm.api :as fs-api]` to my namespace's `:require`, add a call to `(fs-api/remote-connect)` to the top if the file, and then add `#trace` to all the functions that I think might be involved in the bug.  Then I add `#rtrace` to the test case that reproduces my problem, and run the code via my editor's REPL integration.

This works, but is a bit tedious to set up; ideally I wouldn't need to change my code at all to run flowstorm against it.  Am I maybe missing something here?  Is there some magic couple of lines I can send to the REPL via an editor hotkey that will let me instrument everything and hook up my program to the flowstorm UI?

I did notice that stuff like `flow-strom.api/instrument-forms-for-namespaces` is missing for CLJS - is this blocking the dream workflow I just described?

**Comment by jpmonettas** [comment]
Hi @kovasap !

I guess how to connect to flow-storm depends a little on how you start your application and your repl workflow, but this options comes to mind :

If you use some kind of component state management (mount, Sierra components, etc), for cljs flow-storm provides `flow-storm.api/remote-connect` and `flow-storm.api/stop` for starting and stopping  the debugger component. With those you can set it  so your debugger connects every time you start your system. Then just add #trace to whatever you want to debug, use the system and you should see everything under the funnel flow. You don't need to add #rtrace unless you want to control the flow-id, or want to trace a expression at the repl.

If you are not using any kind of state lifecycle library you can add the flow-storm require in your main namespace, and a call to `remote-connect` at the beginning of you main function, so every time your application starts, it will connect to the debugger.
The problem with this is that you need to remove it after, or remember to never commit it, since you don't want it on release.

If you are using a dev namespace for your repl interactions you can require it there, and connect to the debugger as soon as you start your repl with whatever command starts your app.

If you are using emacs and cider (can probably be translated to any other editor/IDE) you can do something like : 

```clojure
(defun clojure-start-debugger ()
  (interactive)
  (cider-nrepl-sync-request:eval "(do (require 'flow-storm.api) (flow-storm.api/remote-connect))"))

(define-key clojure-mode-map (kbd "<f7>") 'clojure-start-debugger)
```
so whenever you need to connect to the debugger you just hit a key.

 > I did notice that stuff like flow-strom.api/instrument-forms-for-namespaces is missing for CLJS

Yes, this isn't supported yet in CLJS together with a bunch of other stuff, check the limitations note here https://jpmonettas.github.io/flow-storm-debugger/user_guide.html#_clojurescript. I'm currently working on a redesign that hopefully will bring CLJS support on par with Clojure.   

I hope that helps!

**Comment by kovasap** [comment]
Thanks for the thorough response.  I'll try getting my editor setup with those REPL calls.

IIUC until the CLJS support is improved I will need to add the trace statements to all functions that might have problems.  There is no way to add a trace to a top level function and then have everything it calls be traced recursively?

**Comment by jpmonettas** [comment]
> IIUC until the CLJS support is improved I will need to add the trace statements to all functions that might have problems

Exactly, until we are able to instrument entire namespaces in ClojureScript

> There is no way to add a trace to a top level function and then have everything it calls be traced recursively?

No, `#trace (some-form...)` is just sugar for `(flow-storm.instrument.forms/instrument (some-form ...))` which basically transform (rewrite) `(some-form ...)` and all of its sub forms so they do exactly the same but trace whats happening. So when tracing a form you just instrument that, and not any other form defined outside.

Does it make sense?

**Comment by kovasap** [comment]
Yes, that makes sense to me!
